# 2025-09-24

### Numpy

In [141]:
import numpy as np

In [4]:
np.__version__

'2.3.3'

In [5]:
L = range(1000)
%timeit L2 = [i **2 for i in L]

40.7 μs ± 4.27 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [7]:
arr = np.arange(100)
%timeit arr2 = arr**2

375 ns ± 23.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [8]:
alist = [1, 2, 3, 4, 5, 6]

In [12]:
print(alist)
print(type(alist))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [17]:
alist = [1, 2, None, 4, 5, 6]

# 단순히 비우면 syntax 오류

In [31]:
alist = [1, 2, 3, 4, 5, 6]

ar1 = np.array(alist)
print(ar1)
print(type(ar1)) # ar1 타입 확인
ar1.dtype # 요소 타입 확인, 정수: int

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


dtype('int64')

In [27]:
ar2 = np.array([1.1, 2.2, 3.3])

print(ar2)
ar2.dtype # 실수: float

[1.1 2.2 3.3]


dtype('float64')

In [30]:
list_data = [1, 2., 3]

ar3 = np.array(list_data, dtype="int") # 정수형으로 변환

print(ar3)
print(ar3.dtype)

[1 2 3]
int64


In [34]:
np.array([1, 2, np.nan, 4])


# 단순히 비우면 syntax 오류

array([ 1.,  2., nan,  4.])

In [35]:
arr1 = np.array([1, 2, 3, 4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

# (4, ) 벡터 (1, 4)가 아닌 이유: (1, 4)는 벡터 형태임 [[]]

[1 2 3 4]
1
(4,)


In [41]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

# (1, 4) 행렬(매트릭스)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [42]:
arr3 = arr2.reshape(-1, 3)

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [45]:
arr4 = arr2.reshape(-1, 7)

print(arr4)
print(arr4.ndim)
print(arr4.shape)

# 사이즈가 맞지 않게 reshape 하는 경우 error

ValueError: cannot reshape array of size 12 into shape (7)

In [46]:
arr4 = arr2.reshape(2, -1, 3)

print(arr4)
print(arr4.ndim)
print(arr4.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [52]:
alist = np.array([1, 2, 3, 4, 5])
blist = np.array([6, 7, 8, 9, 10])

print(alist + blist)
print(alist - blist)
print(alist * blist)
print(alist / blist)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [50]:
alist = np.array([1, 2, 3, 4, 5])
blist = np.array([6, 7, 8, 9])

print(alist + blist)
print(alist - blist)
print(alist * blist)
print(alist / blist)

# 데이터 요소의 수가 맞지 않으면 error

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [51]:
alist = np.array([1, 2, 3, 4, 5])
blist = np.array([6, 7, 8, 9, np.nan])

print(alist + blist)
print(alist - blist)
print(alist * blist)
print(alist / blist)

# nan은 숫자가 아님 -> 분석이 불가능함

[ 7.  9. 11. 13. nan]
[-5. -5. -5. -5. nan]
[ 6. 14. 24. 36. nan]
[0.16666667 0.28571429 0.375      0.44444444        nan]


In [53]:
print(alist + 2)
print(alist - 2)
print(alist * 2)
print(alist / 2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(2 * a + b)
print(a == 2)
print(b > 10)
print((a == 2) & (b > 10))

# and 연산 불가능, 벡터라이즈 연산이기 때문에 & 사용 / or = |

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [65]:
alist = [[0, 1, 2], [3, 4, 5]]

# 0, 1, 5 출력

alist[0][0], alist[0][1], alist[1][2]

(0, 1, 5)

#### 슬라이싱

In [102]:
alist = [[0, 1, 2],
         [3, 4, 5]]

# 0, 1 슬라이싱
# 4, 5 슬라이싱

# 1, 4를 하나의 리스트로 슬라이싱

print(alist[0][:2])
print(alist[1][1:3])
# print([alist[0][0], alist[0][1]])
# print([alist[1][1], alist[1][2]])

aalist = [alist[0][1], alist[1][1]]
print(aalist)

[0, 1]
[4, 5]
[1, 4]


In [ ]:
blist = np.array([[0, 1, 2], [3, 4, 5]])
blist

print(blist[0, 0], blist[0, 1], blist[1, 2])

# 행렬에 대해 인덱싱 가능

0 1 5


In [127]:
# 0, 1 슬라이싱
# 4, 5 슬라이싱

# 1, 4를 하나의 리스트로 슬라이싱

# print(blist[0, 0], blist[0, 1]) 
# print(blist[0, :2]) #[0, 0:2]도 가능
# print(blist[1][1], blist[1][2])

print(blist[0, :2])
print(blist[1, 1:]) #[-1, 1:3]도 가능

# print(blist[0, 1], blist[1, 1])
print(blist[:, 1])
print(blist[[0,1], [1,1]])

[0 1]
[4 5]
[1 4]
[1 4]


In [ ]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])

print(a[0, :3])
print(a[:, 1])
print(a[1, 1:])

print(a[:, :2])

print(a[:, :2])

[0 1 2]
[1 5 9]
[5 6 7]
[[0 1]
 [4 5]
 [8 9]]
[[0 1]
 [4 5]
 [8 9]]
[[1 2 3]
 [5 6 7]]


In [ ]:
# 자유롭게 슬라이싱

clist = np.array([[0, 1, 2, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(clist[:, :2])
print(clist[:2, 1:])
print(clist[1:, 2:])

print(clist[0, :], clist[-1, :])

[[ 0  1]
 [ 5  6]
 [ 9 10]]
[[1 2 4]
 [6 7 8]]
[[ 7  8]
 [11 12]]
[0 1 2 4] [ 9 10 11 12]


In [188]:
# 스텝 사용해서 슬라이싱

clist[:, -2: -1]

array([[ 2],
       [ 7],
       [11]])

#### 팬시 인덱싱

In [ ]:
# 불리언 인덱싱: 개수 매칭 필요

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])

a[idx]

array([0, 2, 4, 6, 8])

In [158]:
a = np.array([1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = [1, 2, 5]

a[idx]

array([0, 1, 4])

In [173]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b[[0, 2]]
b[[0, 1, 2], [1, 2, 0]]

array([2, 6, 7])

In [208]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr % 2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [ ]:
arr[arr % 2 == 0]

# ? gpt 물어보기 -> 뭘 물어보는거임,,?

array([2, 4, 6, 8])

In [179]:
arr[arr % 2 != 0]

array([1, 3, 5, 7])

In [ ]:
# 정수 인덱싱: 개수 무관

a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2])

a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33, 33])

In [202]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8,], [9, 10, 11, 12]])
a

print(a[:, [True, False, False, True]])
print(a[:, [0, 3]])

[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [207]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8,], [9, 10, 11, 12]])
a

a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [210]:
data = np.array([1, 4, 9, 16])

In [ ]:
# 제곱근

np.sqrt(data)

array([1., 2., 3., 4.])

In [ ]:
# 지수

np.exp(data)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [ ]:
# 합

np.sum(data)

np.int64(30)

In [ ]:
# 평균

np.mean(data)

np.float64(7.5)

In [ ]:
# 표준편차

np.std(data)

np.float64(5.678908345800274)

In [222]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [224]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 3의 배수
x[x % 3 == 0]

# 4로 나누면 1이 남는 수
x[x % 4 == 1]

# 3으로 나누면 나누어지고 4로 나누면 1이 남는 수
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

### Pandas (Phython Data Analysis Library)

In [230]:
!pip install pandas


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [140]:
import pandas as pd

In [188]:
df = pd.read_csv("heroes.csv")
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [11]:
pd.options.display.float_format = '{:.0f}'.format

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [15]:
df.describe()

나이   키             재산
count   7   7              5
mean   34 190  2300278000120
std    13  36  5142800956894
min    18 170            600
25%    26 172       50000000
50%    32 177      340000000
75%    39 184     1000000000
max    58 270 11500000000000

In [ ]:
df.head()

# head: defult 앞 5개
# tail: defult 뒤 5개
# 각각 숫자 지정 가능

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000

In [19]:
df['국적']

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object

In [21]:
type(df['국적'])

pandas.core.series.Series

In [ ]:
# 개수

df["국적"].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [ ]:
# 분포도

df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [26]:
df['나이']

0    58
1    45
2    18
3    27
4    33
5    25
6    32
Name: 나이, dtype: int64

In [27]:
df['나이'].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [31]:
# 나이 기준(내림차순)으로 데이터 프레임 정렬

df.nlargest(7, '나이')

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
6  블랙위도우  32    스파이    러시아  170       50000000
3   원더우먼  27     공주  데미스키라  178            NaN
5   캡틴마블  25    파일럿     미국  170      340000000
2  스파이더맨  18   고등학생     미국  177            600

In [32]:
df.nlargest(7, '키')

이름  나이     직업     국적    키             재산
4     헐크  33  핵물리학자     미국  270     1000000000
1     토르  45      신  아스가르드  190            NaN
3   원더우먼  27     공주  데미스키라  178            NaN
2  스파이더맨  18   고등학생     미국  177            600
0   아이언맨  58    CEO     미국  174 11500000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [34]:
df['이름']

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
4       헐크
5     캡틴마블
6    블랙위도우
Name: 이름, dtype: object

In [ ]:
# 시리즈 슬라이싱

df['이름'][:5]

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
4       헐크
Name: 이름, dtype: object

In [41]:
# 데이터 프레임 슬라이싱

df[3:]

이름  나이     직업     국적    키         재산
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [ ]:
# 행과 열을 사용하여 슬라이싱

df.iloc # 번호 인덱스 기반 접근
df.loc # 이름 기반 접근

In [50]:
df.iloc[1]

이름       토르
나이       45
직업        신
국적    아스가르드
키       190
재산      NaN
Name: 1, dtype: object

In [ ]:
# 정수 인덱싱

df.iloc[[1, 3, 6]]

이름  나이   직업     국적    키       재산
1     토르  45    신  아스가르드  190      NaN
3   원더우먼  27   공주  데미스키라  178      NaN
6  블랙위도우  32  스파이    러시아  170 50000000

In [44]:
df.iloc[1:4]

이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

In [48]:
df.iloc[:5, :3]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [51]:
df.loc[1]

이름       토르
나이       45
직업        신
국적    아스가르드
키       190
재산      NaN
Name: 1, dtype: object

In [52]:
df.loc[[1, 3, 6]]

이름  나이   직업     국적    키       재산
1     토르  45    신  아스가르드  190      NaN
3   원더우먼  27   공주  데미스키라  178      NaN
6  블랙위도우  32  스파이    러시아  170 50000000

In [ ]:
df.loc[1:4] # 이름 기반이기 때문에 [포함:포함]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
2  스파이더맨  18   고등학생     미국  177        600
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000

In [54]:
df.loc[:2, ['이름', '직업']]

이름    직업
0   아이언맨   CEO
1     토르     신
2  스파이더맨  고등학생

In [57]:
df.loc[3:, '국적':'재산']

국적    키         재산
3  데미스키라  178        NaN
4     미국  270 1000000000
5     미국  170  340000000
6    러시아  170   50000000

In [58]:
df['나이'] > 30

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool

In [59]:
df[df['나이'] > 30]

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [73]:
# 나이가 30 초과이면서 50 미만인 사람들의 전체 레코드

df['나이'] < 50
df[(df['나이'] > 30) & (df['나이'] < 50)]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [83]:
# 키가 180 이상인 레코드의 이름과 나이 컬럼만 출력

df['키'] >= 180
df[df['키'] >= 180]
df.loc[df['키'] >= 180, ['이름', '나이', '키']]

이름  나이    키
1  토르  45  190
4  헐크  33  270

In [ ]:
# 컬럼 추가

df['전투력'] = 98 # 일괄 지정
df['전투력'] = [100, 99, ...] # 각각 개별 지정

In [93]:
df['전투력'] = 98

In [85]:
df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   98
1     토르  45      신  아스가르드  190            NaN   98
2  스파이더맨  18   고등학생     미국  177            600   98
3   원더우먼  27     공주  데미스키라  178            NaN   98
4     헐크  33  핵물리학자     미국  270     1000000000   98
5   캡틴마블  25    파일럿     미국  170      340000000   98
6  블랙위도우  32    스파이    러시아  170       50000000   98

In [87]:
df['전투력'] -= 5
df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   88
1     토르  45      신  아스가르드  190            NaN   88
2  스파이더맨  18   고등학생     미국  177            600   88
3   원더우먼  27     공주  데미스키라  178            NaN   88
4     헐크  33  핵물리학자     미국  270     1000000000   88
5   캡틴마블  25    파일럿     미국  170      340000000   88
6  블랙위도우  32    스파이    러시아  170       50000000   88

In [ ]:
# 컬럼 삭제 (임시)

df.drop(columns=['전투력'])

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [90]:
df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   88
1     토르  45      신  아스가르드  190            NaN   88
2  스파이더맨  18   고등학생     미국  177            600   88
3   원더우먼  27     공주  데미스키라  178            NaN   88
4     헐크  33  핵물리학자     미국  270     1000000000   88
5   캡틴마블  25    파일럿     미국  170      340000000   88
6  블랙위도우  32    스파이    러시아  170       50000000   88

In [ ]:
df.drop(columns=['전투력'], inplace=True) # 원본 삭제

In [113]:
df

이름  나이     직업   국적    키             재산
0   아이언맨  58    CEO   미국  174 11500000000000
2  스파이더맨  18   고등학생   미국  177            600
4     헐크  33  핵물리학자   미국  270     1000000000
5   캡틴마블  25    파일럿   미국  170      340000000
6  블랙위도우  32    스파이  러시아  170       50000000

In [95]:
df = df.drop(columns=['전투력']) # 원본 삭제

In [162]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [163]:
# NaN = 결측치
# 기입이 되지 않음

df.info() # 결측치 존재 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [164]:
df['재산'].isnull() # 결측치 True

0    False
1     True
2    False
3     True
4    False
5    False
6    False
Name: 재산, dtype: bool

In [165]:
df[df['재산'].isnull()] # 결측치가 존재하는 행

이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [166]:
df.isnull().sum() # 컬럼별 null의 수

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64

In [167]:
df.dropna() # 결측치가 존재하는 행 삭제

이름  나이     직업   국적    키             재산
0   아이언맨  58    CEO   미국  174 11500000000000
2  스파이더맨  18   고등학생   미국  177            600
4     헐크  33  핵물리학자   미국  270     1000000000
5   캡틴마블  25    파일럿   미국  170      340000000
6  블랙위도우  32    스파이  러시아  170       50000000

In [168]:
df = df.dropna()
df

이름  나이     직업   국적    키             재산
0   아이언맨  58    CEO   미국  174 11500000000000
2  스파이더맨  18   고등학생   미국  177            600
4     헐크  33  핵물리학자   미국  270     1000000000
5   캡틴마블  25    파일럿   미국  170      340000000
6  블랙위도우  32    스파이  러시아  170       50000000

In [169]:
df

이름  나이     직업   국적    키             재산
0   아이언맨  58    CEO   미국  174 11500000000000
2  스파이더맨  18   고등학생   미국  177            600
4     헐크  33  핵물리학자   미국  270     1000000000
5   캡틴마블  25    파일럿   미국  170      340000000
6  블랙위도우  32    스파이  러시아  170       50000000

여기서부터 파일 혹은 강의 보고 다시 체크... 오류남 (계속)

In [266]:
df = pd.read_csv('heroes.csv')

In [267]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [268]:
df['재산'].mean()

np.float64(2300278000120.0)

In [269]:
df['재산'].fillna(df['재산'].mean()) # 결측치를 mean 으로 채우기

0   11500000000000
1    2300278000120
2              600
3    2300278000120
4       1000000000
5        340000000
6         50000000
Name: 재산, dtype: float64

In [270]:
df['재산'] = df['재산'].fillna(df['재산'].mean())

In [271]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190  2300278000120
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178  2300278000120
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [297]:
df.fillna(method='ffill') # 이전 값으로 채움

C:\Users\EL65\AppData\Local\Temp\ipykernel_12436\2161014082.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill') # 이전 값으로 채움


이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190  2300278000120
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178  2300278000120
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  33    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [298]:
df = df.fillna(method='ffill')
df.fillna(method='ffill', inplace=True)

C:\Users\EL65\AppData\Local\Temp\ipykernel_12436\903477262.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')
C:\Users\EL65\AppData\Local\Temp\ipykernel_12436\903477262.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)


In [303]:
df.iloc[5, 1] = np.nan # 결측값 할당
np.nan

nan

In [304]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190  2300278000120
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178  2300278000120
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블 NaN    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [305]:
# 나이의 평균값으로 결측치 채우기

df['나이'].mean()
df['나이'].fillna(df['나이'].mean())
df['나이'] = df['나이'].fillna(df['나이'].mean())

In [306]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190  2300278000120
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178  2300278000120
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  36    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [307]:
# 키 뒤 cm 추가

# 함수 사용
def add_cm(height):
    return str(height) + "cm" # 키는 int, 숫자형 데이터로 할당되어 있음. + 문자열을 추가하기 위하여 str 형변환

df['키'].apply(add_cm)


# lambda 사용
df['키'].apply(lambda a: str(a)+'cm')

0    174cm
1    190cm
2    177cm
3    178cm
4    270cm
5    170cm
6    170cm
Name: 키, dtype: object

In [308]:
df['키'] = df['키'].apply(add_cm)

In [309]:
df

이름  나이     직업     국적      키             재산
0   아이언맨  58    CEO     미국  174cm 11500000000000
1     토르  45      신  아스가르드  190cm  2300278000120
2  스파이더맨  18   고등학생     미국  177cm            600
3   원더우먼  27     공주  데미스키라  178cm  2300278000120
4     헐크  33  핵물리학자     미국  270cm     1000000000
5   캡틴마블  36    파일럿     미국  170cm      340000000
6  블랙위도우  32    스파이    러시아  170cm       50000000

In [ ]:
# 만약 cm를 한 번 더 추가한 경우 -> 파이썬 영역

In [311]:
df['키'] = df['키'].apply(add_cm)

In [312]:
df

이름  나이     직업     국적        키             재산
0   아이언맨  58    CEO     미국  174cmcm 11500000000000
1     토르  45      신  아스가르드  190cmcm  2300278000120
2  스파이더맨  18   고등학생     미국  177cmcm            600
3   원더우먼  27     공주  데미스키라  178cmcm  2300278000120
4     헐크  33  핵물리학자     미국  270cmcm     1000000000
5   캡틴마블  36    파일럿     미국  170cmcm      340000000
6  블랙위도우  32    스파이    러시아  170cmcm       50000000

In [313]:
# # 함수 사용
# def add_cm(a):
#     return str(a) + "cm" # 키는 int, 숫자형 데이터로 할당되어 있음. + 문자열을 추가하기 위하여 str 형변환

# df['키'].apply(add_cm)


# # lambda 사용
# df['키'].apply(lambda a: str(a)+'cm')

def remove_cm(b):
    part = b.replace('cmcm', '')
    part_float = float(part)
    return part # or part_float

df['키'] = df['키'].apply(remove_cm)

# cm 하나로 원상복귀 혹은 숫자로 원상복귀 둘 중 1 택

In [314]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190  2300278000120
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178  2300278000120
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  36    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [315]:
# 그룹화

df.groupby('국적') # 그룹으로 묶기
df.groupby('국적')['나이'].mean() # 국적 별 그룹으로 묶은 뒤 나이의 평균값 출력
df.groupby('국적')['재산'].mean() # 국적 별 그룹으로 묶은 뒤 재산의 평균값 출력

국적
데미스키라   2300278000120
러시아          50000000
미국      2875335000150
아스가르드   2300278000120
Name: 재산, dtype: float64